# Generated by Django 4.2.3 on 2023-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('type', models.CharField(choices=[('SALE', 'Sale'), ('PERFORMANCE', 'Performance')], max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, choices=[('DOCTOR', 'Doctor'), ('MASTER', 'Master'), ('BACHELOR', 'Bachelor'), ('JUNIOR_COLLEGE', 'Junior College'), ('HIGH_SCHOOL', 'High School'), ('VOCATIONAL_SCHOOL', 'Vocational School'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('personality', models.CharField(blank=True, max_length=30, null=True)),
                ('habit', models.CharField(blank=True, max_length=50, null=True)),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('advantage', models.CharField(blank=True, max_length=50, null=True)),
                ('speaking_style', models.CharField(blank=True, max_length=50, null=True)),
                ('audience_type', models.CharField(blank=True, max_length=30, null=True)),
                ('worldview', models.TextField(blank=True, max_length=400, null=True)),
                ('personal_statement', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
