# Generated by Django 4.2.3 on 2023-07-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_rename_subject_character_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='worldview',
            new_name='world_view',
        ),
    ]
