# Generated by Django 4.2.3 on 2023-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_rename_type_character_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='education',
            field=models.CharField(blank=True, choices=[('DOCTOR', '博士'), ('MASTER', '硕士'), ('BACHELOR', '本科'), ('JUNIOR_COLLEGE', '大专'), ('HIGH_SCHOOL', '高中'), ('VOCATIONAL_SCHOOL', '中专'), ('OTHER', '其他')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('SALE', '带货'), ('PERFORMANCE', '才艺'), ('KNOWLEDGE', '知识'), ('AFFECTION', '情感')], max_length=50),
        ),
    ]
